### ISSUE TITLE
Add More Hint about Installation in Mac

### ISSUE THREAD

**Issue by ytlw** [ivanallen/dsa#21]
As far as I know, Xcode is not friendly to C++-17, at least in Xcode 9.x it should be like this.
For example, `#include<optional>` will generate fatal error.
In my MacBook Air(version 10.13.6, Xcode version 9.4.1), if I want to compile a single `cpp` file that contains `#include<optional>`, it works well after I install g++-8 through `brew`.
So, I think there is a issue that a better CmakeList is required.

**Comment by jovany-wang** [comment]
Thanks for reporting this.

But I can not see why we need to care what `XCode` complains about? I think It should only related to your compiler, right?  Please correct me if i'm wrong.

**Comment by jovany-wang** [comment]
BTW, If you want to content us as quickly as possible, you can scan the `QR code` in `README.md` to join our DingDing group.

**Comment by ivanallen** [comment]
That is problem. It's block someone to upgrade compiler to support C++17. Maybe we need to consider compatibility with C++11, such as implementing 'optional'.

**Comment by ytlw** [comment]
> That is problem. It's block someone to upgrade compiler to support C++17. Maybe we need to consider compatibility with C++11, such as implementing 'optional'.

I tried `#include<experimental/optional>`, which works well in C++-11. But this project basically is written with C++-17 style, so there is not only one problem ----`#include<optional>`.
In summary, to detect there is a version problem and to recommend the users to upgrade the compiler is better than to write compatible codes.

**Comment by jovany-wang** [comment]
> That is problem. It's block someone to upgrade compiler to support C++17. Maybe we need to consider compatibility with C++11, such as implementing 'optional'.

I don't think so. The perfect solution is to upgrade complier in my view since our code is based on C++17.

**Comment by ytlw** [comment]
> Thanks for reporting this.
> 
> But I can not see why we need to care what `XCode` complains about? I think It should only related to your compiler, right? Please correct me if i'm wrong.

To make sense, in the cmake or make phase, I hope our project can at least remind the users that they should upgrade their compiler.

**Comment by jovany-wang** [comment]
https://github.com/ivanallen/dsa/blob/master/CMakeLists.txt#L6
@inouetoukyou  Does this line is not enough to remind users?

**Comment by ytlw** [comment]
> https://github.com/ivanallen/dsa/blob/master/CMakeLists.txt#L6
> @inouetoukyou Does this line is not enough to remind users?

You are right. Well, this problem is not most important, so let us just leave it aside. 
In fact, for some g++/clang++ which supports `g++ -std=c++17` may also not compile `#<optional>`

**Comment by ivanallen** [comment]
I found references about C++17 implementation status supported by Clang. http://clang.llvm.org/cxx_status.html

**Comment by jovany-wang** [comment]
@ivanallen  According to your ref, it seems Clang(with C++17) doesn't support `optional`.
Maybe the correct way is to implement optional to adapt clang complier.

**Comment by ytlw** [comment]
@jovany-wang I am not familiar with `optional`, but I found there is `<experimental/optional>`. So if it works well, we can use conditional compilation; if it doen't, reimplementing optional is a better way.

**Comment by jovany-wang** [comment]
@inouetoukyou Thanks for your information. I'd like to taste `<experimental/optional>`.

**Comment by jovany-wang** [comment]
I think this issue could be closed since we have already used C++17.
